services:
  redis:
    image: redis:7-alpine
    container_name: pdf_processor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: pdf_processor_app
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - API_BASE_URL=http://localhost:8000
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis_data:
